# GitHub Actions Workflow: Publish to PyPI
# This workflow automates the process of testing and publishing Py-Marqo to PyPI.
# This workflow:
#   1. Runs unit tests using the test.yml workflow
#   2. Publishes the package to PyPi given the unit tests passed

name: Publish to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Run-tests:
    name: Run tests
    uses: ./.github/workflows/test.yml
    secrets: inherit

  Publish-to-PyPi:
    runs-on: ubuntu-latest
    environment: PyPI
    needs:
      - Run-tests

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        cache: "pip"

    - name: Build package
      run: python -m build

    - name: Publish marqo-haystack
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_MARQO_HAYSTACK_TOKEN }}